baseURL = 'https://blog.tomarcher.io/'
title = 'Signal & Syntax by Tom Archer'
languageCode = "en-us"
theme = "hugo-clarity"
canonifyURLs = true

[Params]
  description = "Tom Archer's blog on code, AI, and clean thinking"
  author = "Tom Archer"
  showReadingTime = true
  mainSections = ["posts"]

[Params.sidebar]
  position = "right"
  showRecent = true
  showCategories = true
  showTags = true

[taxonomies]
  tag = "tags"
  category = "categories"
